In [ ]:
#amacımız burada phyton'da scikit-learn kullanarak iris veri setini kullanarak eğitmek, test setine ayırmak.
#train_test_split
#modelin eğitim ve test doğruluğunu gözlemle

In [13]:
#kütüphaneyi içe aktarma
import sklearn, pandas as pd,numpy as np #import= bir kütüphaneyi projeye dahil eder.
from sklearn.datasets import load_iris #load_iris= hazir iris veri setini yükleyen fonksiyon.
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression #LogisticRegression = basit bir maakine öğrenmesi modeli.
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 
# accuracy_score, confusion_matrix, classification_report= sonuçları değerlendirmeye yarayan ölçüm araçlarıdır.


In [14]:
#veri yükleme
iris = load_iris(as_frame=True) # veriyi tablo (DataFrame) getirir
x = iris.data #girdiler, yani her çiçeğin sayısal özellikleri (ör: taç yaprağı uzunluğu)
y = iris. target #çıkış (etiket): hangi çiçek türü

display(x.head()) #ilk 5 satırı gösterir
display(y.head()) 

print("özellik adları:", x.columns.tolist()) #sütun isimlerini listeler
print("sınıf isimleri:", iris.target_names.tolist()) #türlerin isimleri

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

özellik adları: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
sınıf isimleri: ['setosa', 'versicolor', 'virginica']


In [16]:
#eksik veri ve sınıf dengesi kontrolü
null_counts = x.isnull().sum() #her sütunda eksik veri var mı, sayar
print("eksik deper sayıları:\n", null_counts)

print("\nSınıf dağılımı (y):")
print(y.value_counts().sort_index(), "\n") #her sınıftan kaç örnek olduğunu gösterir.
#bu adım, modelin sağlıklı öğrenebilmesi için veri kalitesini kontrol eder.

eksik deper sayıları:
 sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
dtype: int64

Sınıf dağılımı (y):
target
0    50
1    50
2    50
Name: count, dtype: int64 



In [19]:
#veriyi bölme
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y)
#%80 eğitim, %20 test olarak ayırır
#random_state=42 rastgeleliği sabit tutar (aynı sonucu tekrar alırsın)
#stratify=y ise sınıfları orantılı olarak dağıtır 
print(x_train.shape, x_test.shape) #boyutları kontrol ederiz (örneğin 120 eğitim, 30 test örneği

(120, 4) (30, 4)


In [20]:
#model oluşturma ve eğitme
model =LogisticRegression(max_iter=1000) # LogisticRegression()=doğru sınıfa ait olasılıkları hesaplayan bir model
#max_iter=1000 ise öğrenme sırasında iterasyon sınırını attırır (yoksa bazen uyarı:yakınsanmadı hatası alırız)
model.fit(x_train, y_train) #modeli eğitir, yani veriyi öğretir

LogisticRegression(max_iter=1000)

In [21]:
#modeli değerlendirme
train_acc= model.score(x_train, y_train) #score doğruluk oranını döndürür (doğru tahmin sayısı/ toplam)
test_acc= model.score(x_test, y_test)

print(f"eğitim doğruluğu: {train_acc:.3f}") #sayıyı 3 ondalıklı yazdırır
print(f"test doğruluğu: {test_acc:.3f}")

#bu iki değeri karşılaştırırsak:
#eğitim çok yüksek, test düşükse = overfitting (aşırı öğrenme)
#ikisi de düşükse= model yeterince öğrenememiştir



eğitim doğruluğu: 0.975
test doğruluğu: 0.967


In [22]:
#karışıklık matrisi ve sınıflandırma raporu
y_pred= model.predict(x_test) #.predict(X_test)= modelin test verisinde ne tahmin ettiğini döndürür
print("karışıklık matrisi:")
print(confusion_matrix(y_test, y_pred)) #gerçek ve tahmin edilen sınıfları karşılaştırır. köşegen üzerindekiler doğru tahminlerdir.
print("\nSınıflandırma raporu:")
print(classification_report(y_test, y_pred, target_names= iris.target_names)) 
#classification_report= her sınıf için:
#precision(kesinlik)= model 'setosa' dediyse, gerçekten o mu?
#recall(duyarlılık)= tüm gerçek setosaların kaçı bulundu
#f1-score= precision + recall ortalaması

karışıklık matrisi:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]

Sınıflandırma raporu:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.90      0.95        10
   virginica       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [23]:
#tahmin olasılıklarını görmek
y_pred = model.predict(x_test)
probas = model.predict_proba(x_test) #Hher sınıf için olasılık döndürür (örneğin %98 setosa, %2 versicolor)
#böylece modelin eminliği görülebilir